### ISSUE TITLE
Issues with git reset

### ISSUE THREAD

**Issue by AnnJohn** [learn-co-curriculum/html-css-getting-started-with-git#1] opened 2016-06-06 22:50 UTC
When I followed the codealong and tried to do a hard reset in the IDE, got the following.

![screen shot 2016-06-06 at 11 57 39 am](https://cloud.githubusercontent.com/assets/1892150/15840389/909f20ac-2c17-11e6-8192-e1a1453b2067.png)

@loganhasson @pletcher

**Comment by pletcher** [comment] 2016-06-13 14:39
Hi @AnnJohn, I don't see a reset command in there -- is there another screenshot? (Trying to replicate on my own, too.)

**Comment by pletcher** [comment] 2016-06-13 14:43
Hm, I'm not able to reproduce -- the code-along seems to work okay?

**Comment by AnnJohn** [comment] 2016-06-13 19:13
oops wrong screenshot
![reset](https://cloud.githubusercontent.com/assets/1892150/16019846/33e40686-3179-11e6-92df-b4677c8dfbee.png)

maybe i mistyped it? but if it worked fine for you @pletcher maybe we can just close this issue.

**Comment by pletcher** [comment] 2016-06-13 20:09
Ah, okay -- so `--hard` needs to come before the SHA. I think we can close this :)

**Closed as completed by pletcher** 2016-06-13 20:09 UTC
